# -*- coding: utf-8 -*-
"""SMS.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xH5x1MHdND-6o3Bxbz0Zep80rqtV8UUO
"""

import sqlite3

# Connect database
conn = sqlite3.connect("students.db")
cursor = conn.cursor()

# Create table
cursor.execute("""
CREATE TABLE IF NOT EXISTS students (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT,
    age INTEGER,
    course TEXT
)
""")

# Add student
def add_student():
    name = input("Enter name: ")
    age = int(input("Enter age: "))
    course = input("Enter course: ")
    cursor.execute("INSERT INTO students (name, age, course) VALUES (?, ?, ?)", (name, age, course))
    conn.commit()
    print("Student added!")

# View students
def view_students():
    cursor.execute("SELECT * FROM students")
    data = cursor.fetchall()
    for row in data:
        print(row)

# Delete student
def delete_student():
    student_id = int(input("Enter ID to delete: "))
    cursor.execute("DELETE FROM students WHERE id=?", (student_id,))
    conn.commit()
    print("Deleted!")

# Menu
while True:
    print("\n1.Add 2.View 3.Delete 4.Exit")
    choice = input("Enter choice: ")

    if choice == "1":
        add_student()
    elif choice == "2":
        view_students()
    elif choice == "3":
        delete_student()
    elif choice == "4":
        break